metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ${ELASTIC_HOSTS}
    ssl.certificate_authorities: "certs/ca/ca.crt"
    ssl.certificate: "certs/es01/es01.crt"
    ssl.key: "certs/es01/es01.key"
    username: ${ELASTIC_USER}
    password: ${ELASTIC_PASSWORD}
    ssl.enabled: true

  - module: system
    metricsets:
      - cpu
      - load
      - memory
      - network
      - uptime
    enabled: true
    period: 10s
    processes: ['.*']

  - module: system
    metricsets:
      - filesystem
      - fsstat
    period: 10s
    filesystem.ignore_types: [smbfs, proc, autofs, securityfs, squashfs, tmpfs, devtmpfs, cifs, iso9660, udf]

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  allow_older_versions: true
  name: "asgard-agent"
  indices:
    - index: "asgard-metricbeat-%{[agent.version]}-%{+yyyy.MM.dd}"
  ssl:
    certificate: "certs/es01/es01.crt"
    certificate_authorities: "certs/ca/ca.crt"
    key: "certs/es01/es01.key"